name: Anything

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Before checkout
        run: ls -la
        
      - uses: actions/checkout@v4
      
      - name: After checkout
        run: ls -la
